# Site
name: "HackCar"
title: "HackCar"
description: "A Cyber Security Blog"
meta_description: "Cyber Security Research Blog"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
url:
baseurl:
google_analytics: 'UA-46278016-1'
disqus: ''
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  gaz:
    name: Gaz
    display_name: Gaz
    gravatar: 2c91f47a4ebea4e44bcf5393c9dcbf3a
    #gravatar: e56154546cf4be74e393c62d1ae9f9d4
    web: https://www.hackcar.uk
    twitter: https://twitter.com/_GarethP
    description: "Threat Hunter and Malware Analyst"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Pagination
paginate: 6
paginate_path: /page:num/

# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true
#Sitemap
defaults:
  -
    scope:
      path:            "_pages"
    values:
      sitemap:         false
